### ISSUE TITLE
Completion menu constantly refreshing when preview option set

### ISSUE THREAD

**Issue by shawnohare** [zchee/deoplete-go#40] opened 2016-02-12 06:26 UTC
I'm not entirely sure this is a deoplete-go bug per se, but I only notice it while using deoplete with the deoplete-go enabled.  It appears that when the results are being written to the preview menu, an infinite refresh loop is triggered.  See below:

![completion_preview_menu](https://cloud.githubusercontent.com/assets/3992436/13000335/0d8b448e-d10e-11e5-9776-d362d83aaf2d.gif)

When deoplete populates the preview menu using only buffer contents, the menu appears to be drawn as expected.

**Comment by zchee** [comment] 2016-02-12 06:39
@shawnohare Thanks issue :)
I do not use `preview`, so did not notice.
I'll test later.

FYI, If you want to solve right now, echodoc is recommended.
https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L750-L754
http://github.com/Shougo/echodoc.vim

**Comment by zchee** [comment] 2016-02-12 07:03
@shawnohare I am developing `deoplete-jedi`.
https://github.com/zchee/deoplete-jedi

This problem also occurs even Python.
So, maybe caused by `deoplete.nvim` core, or my both code is incorrect.

I will continue to debug...

**Comment by shawnohare** [comment] 2016-02-12 17:36
@zchee Thanks for the info!

If it helps, I actually was using the preview option for `completeopt` on 2016-02-10 without issue.  The issue appeared the following day, for me, after updating all my plugins.

**Comment by nhooyr** [comment] 2016-02-13 03:57
@shawnohare this is a problem with neovim. See neovim/neovim#4036. There was an issue on deoplete as well but I can't find it anymore. Those settings only make it happen less, it will still happen. 

Take a look at my gif here

https://camo.githubusercontent.com/cfdefba43971bd44d466ead357bb296e38d7f88c/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c344b6930316d30314939424f485745302f67697068792e676966

Still have the flicker at the end.

**Comment by Shougo** [comment] 2016-02-13 09:03
It is not deoplete/deoplete-go problem.
It is Vim/neovim feature.  Yes, it should be fixed though.
I don't recommend to use preview window.

**Comment by Shougo** [comment] 2016-02-13 09:06
@nhooyr 

> Still have the flicker at the end.

"At the end"?  Please describe it more clearly.

**Comment by Shougo** [comment] 2016-02-13 09:37
@shawnohare @nhooyr 

Can you test the neovim patch?
https://github.com/neovim/neovim/pull/4036

I think it should be merged.  But more testers are needed.

**Comment by nhooyr** [comment] 2016-02-13 19:04
@Shougo At the end of the gif, where I type `io.Copy` you can see the flicker happen even though i have the preview window disabled. I was just saying that disabling preview window isn't the solution to the problem.

I will test it.

**Comment by Shougo** [comment] 2016-02-14 01:00
It is fixed by neovim/neovim#4036.

**Closed as completed by Shougo** 2016-02-14 01:00 UTC
